[build]
publish = "public"
command ="""\
cd themes/docsy && \
git submodule update -f --init && \
cd ../.. && \
export && \
HUGO_BASEURL=$URL/vscode hugo --source vscode --destination '../public/vscode' --environment production && \
HUGO_BASEURL=$URL/lingua-pupuli/editor-services hugo --source editor-services --destination '../lingua-pupuli/static/editor-services' --environment production && \
HUGO_BASEURL=$URL/lingua-pupuli/editor-syntax hugo --source editor-syntax --destination '../lingua-pupuli/static/editor-syntax' --environment production && \
HUGO_BASEURL=$URL/lingua-pupuli hugo --source lingua-pupuli --destination '../public/lingua-pupuli' --environment production
"""

[build.environment]
  HUGO_VERSION = "0.56.0"
